version: "3.5"

networks:
  network-zabbix:
    driver: bridge

services: 
  mysql-server:
    image: mysql:8.0
    container_name: mysql-zabbix 
    restart: always
    ports:
      - '3306:3306'
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_HOST=172.17.0.1
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD_FILE=secret
    networks:
      - network-zabbix
 

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.2-latest
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
     - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
     - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
     - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
     - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
     - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
     - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
     #- snmptraps:/var/lib/zabbix/snmptraps:rw
      #- "./zabbix/alertscripts:/usr/lib/zabbix/alertscripts"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - DB_SERVER_HOST=172.17.0.1
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_ROOT_PASSWORD_FILE=secret
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.2-latest
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/ssl/apache2:/etc/ssl/apache2:ro
      - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=secret
      # MYSQL_ALLOW_EMPTY_PASSWORD=false
      - DB_SERVER_HOST=172.17.0.1
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix 
      - ZBX_SERVER_HOST=172.17.0.1
      # ZBX_SERVER_PORT=10051
      - ZBX_SERVER_NAME=Composed installation
      # ZBX_DB_ENCRYPTION=true # Available since 5.0.0
      # ZBX_DB_KEY_FILE=/run/secrets/client-key.pem # Available since 5.0.0
      # ZBX_DB_CERT_FILE=/run/secrets/client-cert.pem # Available since 5.0.0
      # ZBX_DB_CA_FILE=/run/secrets/root-ca.pem # Available since 5.0.0
      # ZBX_DB_VERIFY_HOST=false # Available since 5.0.0
      # ZBX_DB_CIPHER_LIST= # Available since 5.0.0
      # ZBX_VAULTDBPATH=
      # ZBX_VAULTURL=https://127.0.0.1:8200
      # VAULT_TOKEN=
      # ZBX_HISTORYSTORAGEURL=http://elasticsearch:9200/ # Available since 3.4.5
      # ZBX_HISTORYSTORAGETYPES=['uint', 'dbl', 'str', 'text', 'log'] # Available since 3.4.5
      # ENABLE_WEB_ACCESS_LOG=true
      # ZBX_MAXEXECUTIONTIME=600
      # ZBX_MEMORYLIMIT=128M
      # ZBX_POSTMAXSIZE=16M
      # ZBX_UPLOADMAXFILESIZE=2M
      # ZBX_MAXINPUTTIME=300
      # ZBX_SESSION_NAME=zbx_sessionid
      # Timezone one of: http://php.net/manual/en/timezones.php
      - PHP_TZ=America/Sao_Paulo
      # ZBX_DENY_GUI_ACCESS=false
      # ZBX_GUI_ACCESS_IP_RANGE=['127.0.0.1']
      # ZBX_GUI_WARNING_MSG=Zabbix is under maintenance.
    depends_on:
      - mysql


  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:ubuntu-5.2-latest
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      #- /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      # ZBX_SOURCEIP=
        # ZBX_DEBUGLEVEL=3
        # ZBX_ENABLEREMOTECOMMANDS=0 # Deprecated since 5.0.0
        # ZBX_LOGREMOTECOMMANDS=0
        # ZBX_HOSTINTERFACE= # Available since 4.4.0
        # ZBX_HOSTINTERFACEITEM= # Available since 4.4.0
        - ZBX_SERVER_HOST=172.18.0.1
        # ZBX_PASSIVE_ALLOW=true
        # ZBX_PASSIVESERVERS=
        # ZBX_ACTIVE_ALLOW=true
        # ZBX_ACTIVESERVERS=
        # ZBX_LISTENIP=
        # ZBX_STARTAGENTS=3
        - ZBX_HOSTNAME=Zabbix server
        # ZBX_HOSTNAMEITEM=system.hostname
        # ZBX_METADATA=
        # ZBX_METADATAITEM=
        # ZBX_REFRESHACTIVECHECKS=120
        # ZBX_BUFFERSEND=5
        # ZBX_BUFFERSIZE=100
        # ZBX_MAXLINESPERSECOND=20
        # ZBX_ALIAS=""
        # ZBX_TIMEOUT=3
        # ZBX_UNSAFEUSERPARAMETERS=0
        # ZBX_LOADMODULE="dummy1.so,dummy2.so,dummy10.so"
        # ZBX_TLSCONNECT=unencrypted
        # ZBX_TLSACCEPT=unencrypted
        # ZBX_TLSCAFILE=
        # ZBX_TLSCRLFILE=
        # ZBX_TLSSERVERCERTISSUER=
        # ZBX_TLSSERVERCERTSUBJECT=
        # ZBX_TLSCERTFILE=
        # ZBX_TLSKEYFILE=
        # ZBX_TLSPSKIDENTITY=
        # ZBX_TLSPSKFILE=
        # ZBX_DENYKEY=system.run[*]
        # ZBX_ALLOWKEY=
 

  

  
