version: "3.5"

networks:
  network-zabbix:
    driver: bridge

zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:ubuntu-5.2-latest
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      #- /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.18.0.1
 

 zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:ubuntu-5.2-latest
    ports:
      - "10061:10051"
    #environment:
      #- ZBX_PROXYMODE=${ZBX_PROXYMODE:-0}
      #- ZBX_HOSTNAME=${ZBX_HOSTNAME:-zabbix-proxy}
      #- ZBX_SERVER_HOST
      #- ZBX_SERVER_PORT=${ZBX_SERVER_PORT:-10051}
      #- ZBX_ACTIVESERVERS
      #- ZBX_METADATA=${ZBX_METADATA:-zabbix-proxy}
      #- ZBX_TLSPSKIDENTITY=${ZBX_TLSPSKIDENTITY:-zabbix-proxy}
      #- ZBX_TLSPSKFILE=${ZBX_TLSPSKFILE:-zabbix-proxy.psk}
      #- ZBX_TLSCONNECT=${ZBX_TLSCONNECT:-psk}
      #- ZBX_TLSACCEPT=${ZBX_TLSACCEPT:-psk}
      # - ZBX_DEBUGLEVEL=${ZBX_DEBUGLEVEL:-1}
      # - ZBX_STARTAGENTS=${ZBX_STARTAGENTS:-100}
      # - ZBX_BUFFERSIZE=${ZBX_BUFFERSIZE:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - snmptraps:/var/lib/zabbix/snmptraps:rw
      #- ./enc:/var/lib/zabbix/enc:ro
    restart: always
    networks:
      - network-zabbix