
version: "3.5"

networks:
  network-zabbix:
    driver: bridge

services: 
 mysql-server:
  image: mysql:8.0
  container_name: mysql-zabbix 
  restart: always
  ports:
   - "3306:3306"
  command:
   - mysqld
   - --character-set-server=utf8
   - --collation-server=utf8_bin
   - --default-authentication-plugin=mysql_native_password
  volumes:
   - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
  environment:
   - MYSQL_HOST=172.17.0.1
   - MYSQL_ROOT_PASSWORD=secret
   - MYSQL_DATABASE=zabbix
   - MYSQL_USER=zabbix
   - MYSQL_PASSWORD=zabbix
  networks:
   - network-zabbix
 

 zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.2-latest
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - "10051:10051"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
     - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
     - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
     - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
     - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
     - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
     - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
     - snmptraps:/var/lib/zabbix/snmptraps:rw
      #- "./zabbix/alertscripts:/usr/lib/zabbix/alertscripts"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - DB_SERVER_HOST=172.17.0.1
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
    depends_on:
      - mysql

   zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.2-latest
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/ssl/apache2:/etc/ssl/apache2:ro
      - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=172.17.0.1
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - ZBX_SERVER_HOST=172.17.0.1
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mysql


 zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:ubuntu-5.2-latest
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      #- /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.18.0.1
 

 zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:ubuntu-5.2-latest
    ports:
      - "10061:10051"
    #environment:
      #- ZBX_PROXYMODE=${ZBX_PROXYMODE:-0}
      #- ZBX_HOSTNAME=${ZBX_HOSTNAME:-zabbix-proxy}
      #- ZBX_SERVER_HOST
      #- ZBX_SERVER_PORT=${ZBX_SERVER_PORT:-10051}
      #- ZBX_ACTIVESERVERS
      #- ZBX_METADATA=${ZBX_METADATA:-zabbix-proxy}
      #- ZBX_TLSPSKIDENTITY=${ZBX_TLSPSKIDENTITY:-zabbix-proxy}
      #- ZBX_TLSPSKFILE=${ZBX_TLSPSKFILE:-zabbix-proxy.psk}
      #- ZBX_TLSCONNECT=${ZBX_TLSCONNECT:-psk}
      #- ZBX_TLSACCEPT=${ZBX_TLSACCEPT:-psk}
      # - ZBX_DEBUGLEVEL=${ZBX_DEBUGLEVEL:-1}
      # - ZBX_STARTAGENTS=${ZBX_STARTAGENTS:-100}
      # - ZBX_BUFFERSIZE=${ZBX_BUFFERSIZE:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - snmptraps:/var/lib/zabbix/snmptraps:rw
      #- ./enc:/var/lib/zabbix/enc:ro
    restart: always
    networks:
      - network-zabbix

  